version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: yasserreslan
      POSTGRES_PASSWORD: yasser13
    networks:
      - digitalize-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script into the container

  backend:
    image: yasserrs/digitalize:backend
    container_name: digitalize-app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - digitalize-network
    links:
      - postgres:postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres-db:5432/mydb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - digitalize-network

  web:
    image: yasserrs/digitalize:web
    container_name: web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - postgres  # Make sure the database is up before starting Next.js
    networks:
      - digitalize-network

networks:
  digitalize-network:
    driver: bridge